<?php

Drunken_Header::setTitle('Error 404');

$content[] = '<div id="content">';
$content[] = '  <div id="content-wrapper">';
$content[] = '    <div id="content-inner">';
$content[] = '      <div id="error">';
$content[] = '        <div id="error-icon" class="fl">';
$content[] = '        </div>';
$content[] = '        <div class="system fl">';
$content[] = '        	System';
$content[] = '        </div>';
$content[] = '        <div class="failure fl">';
$content[] = '        	Fehler';
$content[] = '        </div>';
$content[] = '        <div class="cb"></div>';
$content[] = '        <hr></hr>';
$content[] = '        <div>';
$content[] = '          <div class="head">';
$content[] = '        		Error 404';
$content[] = '          </div>';
$content[] = '          <div class="txt">';
$content[] = '        		Hier ist was schief gelaufen. Sollte dieser Fehler erneut erscheinen, wende dich bitte an einen Autorisierten Mitarbeiter.';
$content[] = '          </div>';
$content[] = '        </div>';
$content[] = '      </div>';
$content[] = '    </div>';
$content[] = '  </div>';
$content[] = '</div>';

?>